---
name: 'eslint'
description: |
  Also need to run:

      npm install --save-dev eslint-config-standard eslint-plugin-standard eslint-plugin-promise

  https://github.com/feross/eslint-config-standard
firstMarker: 0
