---
name: 'eslint'
description: |
  Adds my eslint config

  Also need to run:

      npm install --save-dev eslint-config-standard eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node


  And in your `package.json` scripts, add:

    "lint": "eslint .",
    "pretest": "npm run lint",
firstMarker: 0
